### ISSUE TITLE
Talking about API "Contracts"

### ISSUE THREAD

**Issue by oterhaar** [shopware/portal#10]
Pascal Thesing und Florian Büscher

**Comment by shyim** [comment]
# List of available authorities
```
/merchant-api/authorities
```

# Login
```
/merchant-api/login
```

## Params
```json
{
"email": "",
"password": ""
}
´``

# Registration
```
/merchant-api/register
```

## Params
```json
{
"authority": "",
"email": "",
"password": "",
"name": "",
"firstName": "",
"lastName": "",
"salutation": "",
"street": ""
"zipCode": "",,
"city": "",
"country": "",
"phoneNumber": ""
}

# Profile
```
GET /merchant-api/profile
```

## Response
Returns the profile

```
PATCH /merchant-api/profile
```

## Params:
```
{
"description": "";
phone,
website,
"name": "",
"firstName": "",
"lastName": "",
"salutation": "",
"street": ""
"zipCode": "",,
"city": "",
"country": "",
"phoneNumber": ""
}
```

# Products

List

```
GET /merchant-api/products
```

```
GET /merchant-api/products/[ID]
```

```
POST /merchant-api/products
```

## Params

```json
{
name,
description,
images,

}
```

```
DELETE /merchant-api/products/[ID]
```

**Comment by florianklockenkemper** [comment]
There are still apis missing a think.

**Comment by JanPietrzyk** [comment]
login is done through `sales-channel-api/v1/customer/login`

**Comment by shyim** [comment]
Closed as documented now in https://github.com/shopware/portal/wiki/Merchant-API
