### ISSUE TITLE
You have requested a non-existent service "delivery_package_id"

### ISSUE THREAD

**Issue by seggewiss** [shopware/portal#58]
While running bin/console system:install --force we get the following error.
You have requested a non-existent service "delivery_package_id".

**Comment by King-of-Babylon** [comment]
It reaches.....

**Comment by Christian-Rades** [comment]
https://github.com/shopware/portal/pull/59

**Comment by Christian-Rades** [comment]
Fix should be merged

**Comment by seggewiss** [comment]
Fixed :+1:

**Comment by King-of-Babylon** [comment]
#SomeHateComment......
